dist: xenial
os: linux

language: node_js
node_js:
  - "10"

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run genLicense
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: dist/angular-pwa-starter
  on:
    branch: master
